### ISSUE TITLE
Deprecation Warning when using node 18.

### ISSUE THREAD

**Issue by ssbyoung** [tihonove/stylelint-teamcity-formatter#4]
Hello, I am trying to update my project to node 18 and I got this deprecation warning when using this formatter.

```
[DEP0128] DeprecationWarning: Invalid 'main' field in '/srv/node_modules/stylelint-teamcity-formatter/package.json' of 'lib/index.js'. Please either fix that or report it to the module author
```

Not sure if anyone is actively maintaining this project but I wanted to post here.

**Comment by ekonor** [comment]
This can be avoided by using
`        "scsslintTeamCity": "stylelint 'src/**/*.{css,scss}' --color --quiet --custom-formatter node_modules/stylelint-teamcity-formatter/index.js"`
instead of 
`        "scsslintTeamCity": "stylelint 'src/**/*.{css,scss}' --color --quiet --custom-formatter node_modules/stylelint-teamcity-formatter"`
